### PR TITLE
visual studio paths fix

### PR DESCRIPTION
**Pull request by brucelane**
the sample is still not compiling because of ofxOsc.h not found

### CODE REVIEW

**Comment by kitschpatrol** [comment]
Hi Bruce, thanks for trying out the block. And pardon, the repo's a bit of a mess.

Hmm, ofxOsc.h should not be used at all, since Cinder's core OSC implementation is supposed to be subbed in instead.

Did you define CINDER_AVAILABLE in your preprocessor macros?

**Comment by brucelane** [comment]
I didn't define CINDER_AVAILABLE.
I'm just trying to compile it, will try again soon

**Comment by kitschpatrol** [comment]
I just pushed fixes for sample compilation on Windows and Mac. Let me know if you're still having trouble compiling. (Fixed some paths and added the CINDER_AVAILABLE definition to the Windows project.)

**Comment by brucelane** [comment]
I just tryed with CINDER_AVAILABLE and your fixes, I still got some errors I don't know how to fix

**Comment by kitschpatrol** [comment]
Can you post the errors please?

**Comment by brucelane** [comment]
image

**Comment by kitschpatrol** [comment]
Thank you. I see now that my earlier fixes only made it into the 64 bit VC project config. I've just now updated and pushed what should be a fix for both architectures.

**Comment by brucelane** [comment]
yay!
image
we can close this PR now, thank you!
now, how can I use it?

**Comment by brucelane** [comment]
capture d ecran 2016-07-30 a 10 55 11
it doesn't connect...

**Comment by kitschpatrol** [comment]
Does the sample work? I just tested it from master with success. If the sample doesn't work, let's debug that first. If the sample does work, can you share your RemoteUI setup code?

screen shot 2016-07-30 at 12 01 38 pm

**Comment by brucelane** [comment]
I haven't touched anything in the code

**Comment by brucelane** [comment]
the oF App is on Mac and the Cinder part is on a Windows Pc, the ip address is correct

**Comment by brucelane** [comment]
which is the port I have to use? it's the only thing I'm not sure about

**Comment by kitschpatrol** [comment]
The port should be logged to the console on the windows side when the app starts up. Or you can specify a port number manually by passing it to RUI_SETUP.

Console log from the sample app:
screen shot 2016-07-30 at 12 40 24 pm

**Comment by brucelane** [comment]
ok then it's binding to the wrong network interface:
|info   | ofxRemoteUIServer::setup[1098] Broacasting my presence every 1 sec at this broadcast IP 169.254.255.255:25748
|info   | ofxRemoteUIServer::setup[1136] listening for commands at 169.254.80.80:18171
|warning| ofxRemoteUIServer::loadFromXMLv1[2668] Loading XML ofxRemoteUISettings.xml with older format. Be aware that it will be saved with the new format!
|verbose| RemoteUIBasicApp::setup[87] 
I disable it, and now it works!!!!!
Thank you very much

**Comment by kitschpatrol** [comment]
Great! Feel free to open issues if you run into anything else.

**Pull request closed without merging**
